version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
